import {firebaseConfig} from './firebase-config.js';
import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import {getAuth,signInAnonymously} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import {getFirestore,doc,getDoc,getDocs,collection,deleteDoc,onSnapshot,serverTimestamp,runTransaction,writeBatch,query,orderBy,where,limit,setDoc} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
const DEFAULT_WORDS=[{text:'いや',points:1},{text:'でも',points:1},{text:'いや～でも～',points:1},{text:'ん～（甘え声）',points:2},{text:'ラニーニャ',points:3},{text:'エルニーニョ',points:3},{text:'スノボ',points:3},{text:'あれので',points:4},{text:'これので',points:4},{text:'それので',points:4},{text:'あれじゃない？（言うことを考える時間稼ぎ）',points:4},{text:'マウント',points:5},{text:'腹減った',points:5},{text:'ニセコでスマホを無くした話',points:5},{text:'紅ショウガの許可申請',points:5},{text:'モンストコラボの話',points:5},{text:'近ちゃんはそんなこと言わない',points:10}];
const $=s=>document.querySelector(s);let db,user,adminMode=false,currentRoom='',rooms=[],templates=[],words=[],members=[],memberWords=[],events=[],roomSubs=[],lobbySubs=[],selectMode='load',toastTimer;
const number=v=>typeof v==='number'&&Number.isFinite(v)?v:0;const playerName=()=>$('#playerName').value.trim()||localStorage.getItem('kp-name')||'';const id=()=>crypto.randomUUID().replaceAll('-','').slice(0,16);
function toast(t){const e=$('#toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.add('hidden'),2600)}function error(label,e){console.error(label,e);toast(label+': '+e.message)}function status(t,c){$('#status').textContent=t;$('#status').className='status '+c}function color(p){return p>=10?'#c72f45':p>=5?'#e0782d':p>=4?'#bd8b12':p>=3?'#2f8b68':p>=2?'#2b78ba':'#6656e8'}
async function init(){const app=initializeApp(firebaseConfig),auth=getAuth(app);db=getFirestore(app);user=(await signInAnonymously(auth)).user;$('#playerName').value=localStorage.getItem('kp-name')||'';await ensureDefaultTemplate();status('オンライン','ok');$('#joinBtn').disabled=$('#adminJoinBtn').disabled=false}
async function ensureDefaultTemplate(){const r=doc(db,'templates','arai');await runTransaction(db,async tx=>{if(!(await tx.get(r)).exists())tx.set(r,{name:'新井',words:DEFAULT_WORDS,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})})}
function login(admin){if(!playerName())return toast('表示名を入力してください');if(admin&&$('#adminPassword').value!=='UNKO')return toast('管理者パスワードが違います');adminMode=admin;localStorage.setItem('kp-name',playerName());$('#adminPassword').value='';$('#setup').classList.add('hidden');$('#lobby').classList.remove('hidden');subscribeLobby()}
function subscribeLobby(){lobbySubs.forEach(f=>f());lobbySubs=[onSnapshot(query(collection(db,'rooms'),orderBy('createdAt','desc')),s=>{rooms=s.docs.map(d=>({id:d.id,...d.data()})).filter(r=>r.id!=='MAIN00'&&r.name);renderLobby()},e=>error('部屋一覧の同期エラー',e)),onSnapshot(query(collection(db,'templates'),orderBy('createdAt')),s=>{templates=s.docs.map(d=>({id:d.id,...d.data()}));renderLobby()},e=>error('得点表一覧の同期エラー',e))]}
function fillSelect(sel){sel.replaceChildren();templates.forEach(t=>{const o=document.createElement('option');o.value=t.id;o.textContent=t.name;sel.append(o)})}
function renderLobby(){const l=$('#roomList');l.replaceChildren();rooms.forEach(r=>{const b=document.createElement('button');b.className='roomCard';b.innerHTML='<strong></strong><span></span>';b.children[0].textContent=r.name;b.children[1].textContent='得点表: '+(r.templateName||'未設定');b.onclick=()=>enterRoom(r.id);l.append(b)});$('#roomEmpty').classList.toggle('hidden',rooms.length>0);fillSelect($('#createTemplateSelect'));fillSelect($('#templateSelect'));$('#templateCount').textContent=`保存済み ${templates.length}件`}
async function createRoom(e){e.preventDefault();const name=$('#newRoomName').value.trim(),t=templates.find(x=>x.id===$('#createTemplateSelect').value);if(!name||!t)return toast('部屋名と得点表を選択してください');const roomId=id(),b=writeBatch(db);b.set(doc(db,'rooms',roomId),{name,templateId:t.id,templateName:t.name,createdAt:serverTimestamp(),createdBy:user.uid});(t.words||[]).forEach((w,i)=>b.set(doc(collection(db,'rooms',roomId,'words')),{text:w.text,points:number(w.points),count:0,totalScore:0,order:i,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));await b.commit();$('#roomDialog').close();$('#newRoomName').value='';await enterRoom(roomId)}
async function enterRoom(roomId){const rs=await getDoc(doc(db,'rooms',roomId));if(!rs.exists())return toast('部屋が見つかりません');currentRoom=roomId;const r=rs.data();$('#lobby').classList.add('hidden');$('#game').classList.remove('hidden');$('#roomName').textContent=r.name;$('#role').textContent=adminMode?'管理者：参加者削除・全リセットが可能':'得点順、同点は50音順';$('#resetAllBtn').classList.toggle('hidden',!adminMode);const mr=doc(db,'rooms',roomId,'members',user.uid),old=await getDoc(mr);await setDoc(mr,old.exists()?{name:playerName(),updatedAt:serverTimestamp()}:{uid:user.uid,name:playerName(),joinedAt:serverTimestamp(),lastSeenAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});words=[];members=[];memberWords=[];events=[];renderAll();roomSubs.forEach(f=>f());roomSubs=[onSnapshot(collection(db,'rooms',roomId,'words'),s=>{words=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()},e=>error('得点表の同期エラー',e)),onSnapshot(collection(db,'rooms',roomId,'members'),s=>{members=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()},e=>error('参加者の同期エラー',e)),onSnapshot(collection(db,'rooms',roomId,'memberWords'),s=>{memberWords=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()},e=>error('スコアの同期エラー',e)),onSnapshot(query(collection(db,'rooms',roomId,'events'),orderBy('occurredAt','desc'),limit(100)),s=>{events=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()},e=>error('統計の同期エラー',e))]}
const sortedWords=()=>[...words].sort((a,b)=>number(a.points)-number(b.points)||String(a.text).localeCompare(String(b.text),'ja'));const active=()=>new Set(members.map(m=>m.uid));function wordCount(wordId){const a=active();return memberWords.reduce((s,x)=>s+(a.has(x.uid)&&x.wordId===wordId?number(x.count):0),0)}
function renderAll(){renderWords();renderMembers();renderStats()}
function renderWords(){const l=$('#wordList');l.replaceChildren();for(const w of sortedWords()){const p=number(w.points),mine=number(memberWords.find(x=>x.uid===user.uid&&x.wordId===w.id)?.count),e=document.createElement('article');e.className=`word${p>=10?' ten':''}`;e.style.setProperty('--accent',color(p));e.innerHTML=`<div><h3></h3><div class="meta">1回 <b>${p>=0?'+':''}${p}点</b> ・ 全員 ${wordCount(w.id)}回</div><div class="actions"><button class="icon edit">編集</button><button class="icon del">削除</button></div></div><div class="counter"><span class="count">${mine}</span><button class="minus" ${mine<=0?'disabled':''}>−</button><button class="plus">＋</button></div>`;e.querySelector('h3').textContent=w.text;e.querySelector('.edit').onclick=()=>openEditor(w);e.querySelector('.del').onclick=()=>removeWord(w);e.querySelector('.minus').onclick=()=>adjust(w,-1);e.querySelector('.plus').onclick=()=>adjust(w,1);l.append(e)}$('#scoreTotal').textContent=words.reduce((s,w)=>s+wordCount(w.id)*number(w.points),0);$('#countTotal').textContent=words.reduce((s,w)=>s+wordCount(w.id),0);$('#empty').classList.toggle('hidden',words.length>0)}
function renderMembers(){const pm=new Map(words.map(w=>[w.id,number(w.points)])),totals=new Map(members.map(m=>[m.uid,{m,count:0,score:0}]));memberWords.forEach(x=>{const t=totals.get(x.uid);if(t){t.count+=number(x.count);t.score+=number(x.count)*(pm.get(x.wordId)||0)}});const l=$('#memberList');l.replaceChildren();[...totals.values()].sort((a,b)=>b.score-a.score||b.count-a.count).forEach(x=>{const e=document.createElement('div');e.className='member';e.innerHTML=`<div class="memberName"></div><div class="memberStat"><span>カウント</span><strong>${x.count}</strong></div><div class="memberStat"><span>得点</span><strong>${x.score}</strong></div>`;e.querySelector('.memberName').textContent=x.m.name+(x.m.uid===user.uid?'（自分）':'');if(adminMode&&x.m.uid!==user.uid){const b=document.createElement('button');b.className='memberDelete';b.textContent='削除';b.onclick=()=>deleteMember(x.m);e.append(b)}l.append(e)});$('#memberCount').textContent=`${members.length}人`}
function canvas(id,h){const c=$(id),d=devicePixelRatio||1,w=c.clientWidth||600;c.width=w*d;c.height=h*d;const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);return[x,w]}
function renderStats(){const d=words.map(w=>({...w,c:wordCount(w.id)})).sort((a,b)=>b.c-a.c).slice(0,10),[x,w]=canvas('#statsChart',230),max=Math.max(1,...d.map(v=>v.c));x.font='12px system-ui';d.forEach((v,i)=>{const y=i*21,b=(w-180)*v.c/max;x.fillStyle=color(v.points);x.globalAlpha=.25;x.fillRect(150,y,b,15);x.globalAlpha=1;x.fillStyle='#303247';x.fillText(v.text.slice(0,17),2,y+12);x.fillText(v.c,155+b,y+12)});drawTimeline()}
function drawTimeline(){
  const [x,w]=canvas('#timelineChart',280),leg=$('#timelineLegend');
  leg.replaceChildren();
  const activeUsers=active();
  const data=events.map(e=>({...e,date:e.occurredAt?.toDate?.()})).filter(e=>e.date&&activeUsers.has(e.uid)).sort((a,b)=>a.date-b.date);
  const H=280,L=52,R=18,T=18,B=48,plotW=Math.max(1,w-L-R),plotH=H-T-B;
  x.font='11px system-ui';x.lineWidth=1;
  if(!data.length){
    x.strokeStyle='#aeb2c2';x.beginPath();x.moveTo(L,T);x.lineTo(L,H-B);x.lineTo(w-R,H-B);x.stroke();
    x.fillStyle='#777b90';x.textAlign='center';x.textBaseline='middle';x.fillText('まだ発言データがありません',L+plotW/2,T+plotH/2);
    x.save();x.translate(14,T+plotH/2);x.rotate(-Math.PI/2);x.fillText('累計回数',0,0);x.restore();x.textBaseline='top';x.fillText('時刻',L+plotW/2,H-17);return;
  }
  const names=[...new Set(data.map(e=>e.wordText))],pal=new Map(names.map((t,i)=>[t,`hsl(${i*67%360} 65% 48%)`])),series=new Map(names.map(t=>[t,[]])),cum=new Map(names.map(t=>[t,0]));
  data.forEach(e=>{const c=Math.max(0,(cum.get(e.wordText)||0)+number(e.delta));cum.set(e.wordText,c);series.get(e.wordText).push({date:e.date,count:c})});
  const minMs=data[0].date.getTime(),lastMs=data.at(-1).date.getTime(),maxMs=lastMs===minMs?minMs+60000:lastMs,maxCount=Math.max(1,...[...series.values()].flat().map(p=>p.count));
  x.textBaseline='middle';
  for(let i=0;i<=4;i++){const value=Math.round(maxCount*i/4),py=T+plotH-plotH*i/4;x.strokeStyle='#e5e7ef';x.beginPath();x.moveTo(L,py);x.lineTo(w-R,py);x.stroke();x.fillStyle='#676b7e';x.textAlign='right';x.fillText(String(value),L-7,py)}
  for(let i=0;i<=4;i++){const px=L+plotW*i/4,ms=minMs+(maxMs-minMs)*i/4;x.strokeStyle='#eef0f5';x.beginPath();x.moveTo(px,T);x.lineTo(px,H-B);x.stroke();x.fillStyle='#676b7e';x.textAlign=i===0?'left':i===4?'right':'center';x.textBaseline='top';x.fillText(new Date(ms).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}),px,H-B+8)}
  x.strokeStyle='#8b8fa1';x.lineWidth=1.25;x.beginPath();x.moveTo(L,T);x.lineTo(L,H-B);x.lineTo(w-R,H-B);x.stroke();
  for(const [name,points] of series){x.strokeStyle=pal.get(name);x.fillStyle=pal.get(name);x.lineWidth=2;x.beginPath();points.forEach((p,i)=>{const px=L+(p.date.getTime()-minMs)/(maxMs-minMs)*plotW,py=T+plotH-p.count/maxCount*plotH;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();points.forEach(p=>{const px=L+(p.date.getTime()-minMs)/(maxMs-minMs)*plotW,py=T+plotH-p.count/maxCount*plotH;x.beginPath();x.arc(px,py,3.2,0,Math.PI*2);x.fill()});const item=document.createElement('span');item.className='legendItem';const dot=document.createElement('i');dot.style.background=pal.get(name);item.append(dot,document.createTextNode(name));leg.append(item)}
  x.fillStyle='#565a70';x.font='12px system-ui';x.save();x.translate(14,T+plotH/2);x.rotate(-Math.PI/2);x.textAlign='center';x.textBaseline='middle';x.fillText('累計回数',0,0);x.restore();x.textAlign='center';x.textBaseline='top';x.fillText('時刻',L+plotW/2,H-17);
}
async function adjust(w,delta){const wr=doc(db,'rooms',currentRoom,'words',w.id),mr=doc(db,'rooms',currentRoom,'memberWords',`${user.uid}_${w.id}`),er=doc(collection(db,'rooms',currentRoom,'events'));await runTransaction(db,async tx=>{const[ws,ms]=await Promise.all([tx.get(wr),tx.get(mr)]),v=ws.data(),c=ms.exists()?ms.data().count:0;if(delta<0&&c<=0)throw Error('取り消せません');tx.update(wr,{count:v.count+delta,totalScore:v.totalScore+v.points*delta,updatedAt:serverTimestamp()});ms.exists()?tx.update(mr,{count:c+delta,updatedAt:serverTimestamp()}):tx.set(mr,{uid:user.uid,wordId:w.id,count:1,updatedAt:serverTimestamp()});tx.set(er,{uid:user.uid,name:playerName(),wordId:w.id,wordText:w.text,delta,points:w.points,occurredAt:serverTimestamp()})})}
function openEditor(w={}){$('#editId').value=w.id||'';$('#wordText').value=w.text||'';$('#wordPoints').value=w.points??1;$('#editorTitle').textContent=w.id?'言葉を編集':'言葉を追加';$('#editor').showModal()}async function saveWord(e){e.preventDefault();const idv=$('#editId').value,text=$('#wordText').value.trim(),points=Number($('#wordPoints').value),r=idv?doc(db,'rooms',currentRoom,'words',idv):doc(collection(db,'rooms',currentRoom,'words'));if(idv){const s=await getDoc(r),old=s.data();await setDoc(r,{...old,text,points,totalScore:number(old.count)*points,updatedAt:serverTimestamp()})}else await setDoc(r,{text,points,count:0,totalScore:0,order:Date.now(),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});$('#editor').close()}
async function removeWord(w){if(confirm(`「${w.text}」を削除しますか？`))await deleteDoc(doc(db,'rooms',currentRoom,'words',w.id))}async function deleteMember(m){const s=await getDocs(query(collection(db,'rooms',currentRoom,'memberWords'),where('uid','==',m.uid))),b=writeBatch(db);s.forEach(d=>b.delete(d.ref));b.delete(doc(db,'rooms',currentRoom,'members',m.uid));await b.commit()}
async function resetAll(){if(!adminMode||!confirm('この部屋の全スコアと統計をリセットしますか？'))return;const[m,e]=await Promise.all([getDocs(collection(db,'rooms',currentRoom,'memberWords')),getDocs(collection(db,'rooms',currentRoom,'events'))]),b=writeBatch(db);m.forEach(d=>b.delete(d.ref));e.forEach(d=>b.delete(d.ref));words.forEach(w=>b.update(doc(db,'rooms',currentRoom,'words',w.id),{count:0,totalScore:0,updatedAt:serverTimestamp()}));await b.commit()}
async function saveTemplate(e){e.preventDefault();const name=$('#templateName').value.trim(),existing=templates.find(t=>t.name.trim().toLowerCase()===name.toLowerCase());if(!existing&&templates.length>=5)return toast('得点表は最大5個です');await setDoc(doc(db,'templates',existing?.id||id()),{name,words:sortedWords().map(w=>({text:w.text,points:w.points})),createdAt:existing?.createdAt||serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});$('#templateDialog').close();toast(existing?'得点表を上書きしました':'得点表を保存しました')}
function openTemplateSelect(mode){selectMode=mode;fillSelect($('#templateSelect'));$('#selectTemplateTitle').textContent=mode==='load'?'得点表を読み込む':'得点表を削除';$('#selectTemplateNote').textContent=mode==='load'?'読み込むと、この部屋のスコアと統計はリセットされます。':'削除後も、その得点表から作成済みの部屋は残ります。';$('#selectTemplateDialog').showModal()}
async function executeTemplate(e){e.preventDefault();const t=templates.find(x=>x.id===$('#templateSelect').value);if(!t)return;if(selectMode==='delete'){if(!adminMode)return toast('管理者のみ削除できます');if(t.id==='arai')return toast('「新井」は削除できません');if(confirm(`「${t.name}」を削除しますか？`))await deleteDoc(doc(db,'templates',t.id));$('#selectTemplateDialog').close();return}if(!confirm(`「${t.name}」を読み込みますか？`))return;const[ws,ms,es]=await Promise.all([getDocs(collection(db,'rooms',currentRoom,'words')),getDocs(collection(db,'rooms',currentRoom,'memberWords')),getDocs(collection(db,'rooms',currentRoom,'events'))]),b=writeBatch(db);ws.forEach(d=>b.delete(d.ref));ms.forEach(d=>b.delete(d.ref));es.forEach(d=>b.delete(d.ref));(t.words||[]).forEach((w,i)=>b.set(doc(collection(db,'rooms',currentRoom,'words')),{...w,count:0,totalScore:0,order:i,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));b.update(doc(db,'rooms',currentRoom),{templateId:t.id,templateName:t.name});await b.commit();$('#selectTemplateDialog').close()}
function backLobby(){roomSubs.forEach(f=>f());roomSubs=[];currentRoom='';$('#game').classList.add('hidden');$('#lobby').classList.remove('hidden')}function backLogin(){lobbySubs.forEach(f=>f());lobbySubs=[];adminMode=false;$('#lobby').classList.add('hidden');$('#setup').classList.remove('hidden')}
$('#joinBtn').onclick=()=>login(false);$('#adminJoinBtn').onclick=()=>login(true);$('#newRoomBtn').onclick=()=>{fillSelect($('#createTemplateSelect'));$('#roomDialog').showModal()};$('#roomForm').onsubmit=e=>createRoom(e).catch(x=>error('部屋作成エラー',x));$('#lobbyBackBtn').onclick=backLobby;$('#loginBackBtn').onclick=backLogin;$('#addBtn').onclick=()=>openEditor();$('#editorForm').onsubmit=e=>saveWord(e).catch(x=>error('言葉保存エラー',x));$('#saveTemplateBtn').onclick=()=>$('#templateDialog').showModal();$('#templateForm').onsubmit=e=>saveTemplate(e).catch(x=>error('得点表保存エラー',x));$('#loadTemplateBtn').onclick=()=>openTemplateSelect('load');$('#deleteTemplateBtn').onclick=()=>openTemplateSelect('delete');$('#selectTemplateForm').onsubmit=e=>executeTemplate(e).catch(x=>error('得点表操作エラー',x));$('#resetAllBtn').onclick=()=>resetAll().catch(x=>error('リセットエラー',x));document.querySelectorAll('.cancel').forEach(b=>b.onclick=()=>b.closest('dialog').close());window.addEventListener('resize',renderStats);init().catch(e=>{status('接続エラー','bad');error('初期化エラー',e)});
