import {firebaseConfig} from './firebase-config.js';
import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import {getAuth,signInAnonymously} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import {getFirestore,doc,getDoc,getDocs,collection,deleteDoc,updateDoc,onSnapshot,serverTimestamp,runTransaction,writeBatch,query,orderBy,where,limit} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
const DEFAULT_WORDS=[{text:'いや',points:1},{text:'でも',points:1},{text:'いや～でも～',points:1},{text:'ん～（甘え声）',points:2},{text:'ラニーニャ',points:3},{text:'エルニーニョ',points:3},{text:'スノボ',points:3},{text:'あれので',points:4},{text:'これので',points:4},{text:'それので',points:4},{text:'あれじゃない？（言うことを考える時間稼ぎ）',points:4},{text:'マウント',points:5},{text:'腹減った',points:5},{text:'ニセコでスマホを無くした話',points:5},{text:'紅ショウガの許可申請',points:5},{text:'モンストコラボの話',points:5},{text:'近ちゃんはそんなこと言わない',points:10}];
const MAIN_ROOM='MAIN00',$=s=>document.querySelector(s);let db,user,room='',words=[],members=[],memberWords=[],events=[],unsubs=[],toastTimer,adminMode=false;
const isAdmin=()=>adminMode;
function status(t,c){$('#status').textContent=t;$('#status').className=`status ${c}`}function toast(t){const e=$('#toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.add('hidden'),2300)}
function playerName(){return $('#playerName').value.trim()||localStorage.getItem('kp-name')||''}function number(v){return typeof v==='number'&&Number.isFinite(v)?v:0}function color(p){return p>=10?'#c72f45':p>=5?'#e0782d':p>=4?'#bd8b12':p>=3?'#2f8b68':p>=2?'#2b78ba':'#6656e8'}
function sortedWords(){return [...words].sort((a,b)=>number(a.points)-number(b.points)||String(a.text).localeCompare(String(b.text),'ja',{sensitivity:'base'}))}
async function init(){$('#playerName').value=localStorage.getItem('kp-name')||'';const app=initializeApp(firebaseConfig),auth=getAuth(app);db=getFirestore(app);user=(await signInAnonymously(auth)).user;status('オンライン','ok');$('#joinBtn').disabled=false;$('#adminJoinBtn').disabled=false;if(playerName())await joinRoom(false)}
async function joinRoom(asAdmin=false){if(!user)return;const name=playerName();if(asAdmin&&$('#adminPassword').value!=='UNKO')return toast('管理者パスワードが違います');adminMode=asAdmin;$('#adminPassword').value='';if(!name)return toast('表示名を入力してください');localStorage.setItem('kp-name',name);const rr=doc(db,'rooms',MAIN_ROOM);await runTransaction(db,async tx=>{const s=await tx.get(rr);if(!s.exists()){tx.set(rr,{createdAt:serverTimestamp()});DEFAULT_WORDS.forEach((w,i)=>tx.set(doc(collection(db,'rooms',MAIN_ROOM,'words')),{...w,count:0,totalScore:0,order:i,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}))}});await enter()}
async function enter(){room=MAIN_ROOM;$('#setup').classList.add('hidden');$('#game').classList.remove('hidden');$('#role').textContent=isAdmin()?'管理者：参加者の削除ができます':'得点順、同点は50音順';const mr=doc(db,'rooms',room,'members',user.uid);await runTransaction(db,async tx=>{const s=await tx.get(mr);if(s.exists())tx.update(mr,{name:playerName(),lastSeenAt:serverTimestamp(),updatedAt:serverTimestamp()});else tx.set(mr,{uid:user.uid,name:playerName(),joinedAt:serverTimestamp(),lastSeenAt:serverTimestamp(),updatedAt:serverTimestamp()})});unsubs.forEach(f=>f());unsubs=[onSnapshot(collection(db,'rooms',room,'words'),s=>{words=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()}),onSnapshot(collection(db,'rooms',room,'members'),s=>{members=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()}),onSnapshot(collection(db,'rooms',room,'memberWords'),s=>{memberWords=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()}),onSnapshot(query(collection(db,'rooms',room,'events'),orderBy('occurredAt','desc'),limit(100)),s=>{events=s.docs.map(d=>({id:d.id,...d.data()}));renderStats()})]}
function renderAll(){renderWords();renderMembers();renderStats()}
function renderWords(){const list=$('#wordList');list.replaceChildren();for(const w of sortedWords()){const p=number(w.points),mine=number(memberWords.find(x=>x.uid===user.uid&&x.wordId===w.id)?.count),el=document.createElement('article');el.className=`word${p>=10?' ten':''}`;el.style.setProperty('--accent',color(p));el.innerHTML=`<div><h3></h3><div class="meta">1回 <b>${p>=0?'+':''}${p}点</b> ・ 全員 ${number(w.count)}回</div><div class="actions"><button class="icon edit">編集</button><button class="icon del">削除</button></div></div><div class="counter"><span class="count">${mine}</span><button class="minus" ${mine<=0?'disabled':''}>−</button><button class="plus">＋</button></div>`;el.querySelector('h3').textContent=w.text;el.querySelector('.edit').onclick=()=>openEditor(w);el.querySelector('.del').onclick=()=>removeWord(w);el.querySelector('.minus').onclick=()=>adjust(w,-1);el.querySelector('.plus').onclick=()=>adjust(w,1);list.append(el)}$('#scoreTotal').textContent=String(words.reduce((s,w)=>s+number(w.totalScore),0));$('#countTotal').textContent=String(words.reduce((s,w)=>s+number(w.count),0));$('#empty').classList.toggle('hidden',words.length>0)}
function totals(){const p=new Map(words.map(w=>[w.id,number(w.points)])),m=new Map(members.map(x=>[x.uid,{member:x,count:0,score:0}]));for(const x of memberWords){const t=m.get(x.uid);if(t){t.count+=number(x.count);t.score+=number(x.count)*(p.get(x.wordId)||0)}}return [...m.values()].sort((a,b)=>b.score-a.score||b.count-a.count||String(a.member.name).localeCompare(String(b.member.name),'ja'))}
function renderMembers(){const list=$('#memberList');list.replaceChildren();for(const x of totals()){const row=document.createElement('div');row.className='member';const del=isAdmin()&&x.member.uid!==user.uid?'<button class="memberDelete">削除</button>':'';row.innerHTML=`<div class="memberName"></div><div class="memberStat"><span>カウント</span><strong>${x.count}</strong></div><div class="memberStat"><span>得点</span><strong>${x.score}</strong></div>${del}`;row.querySelector('.memberName').textContent=x.member.name+(x.member.uid===user.uid?'（自分）':'');if(del)row.querySelector('.memberDelete').onclick=()=>deleteMember(x.member);list.append(row)}$('#memberCount').textContent=`${members.length}人`}
function renderStats(){const body=$('#statsBody');body.replaceChildren();const data=[...words].sort((a,b)=>number(b.count)-number(a.count)||String(a.text).localeCompare(String(b.text),'ja'));for(const w of data){const r=document.createElement('tr');r.innerHTML='<td></td><td>'+number(w.count)+'</td><td>'+number(w.totalScore)+'</td>';r.firstChild.textContent=w.text;body.append(r)}drawChart(data.slice(0,10));const eb=$('#eventBody');eb.replaceChildren();for(const e of events.slice(0,30)){const w=words.find(x=>x.id===e.wordId);const r=document.createElement('tr'),date=e.occurredAt?.toDate?.();r.innerHTML='<td></td><td></td><td></td><td></td>';r.children[0].textContent=date?date.toLocaleString('ja-JP'):'同期中';r.children[1].textContent=e.name||members.find(x=>x.uid===e.uid)?.name||'不明';r.children[2].textContent=e.wordText||w?.text||'削除済み';r.children[3].textContent=(e.delta>0?'+':'')+e.delta;eb.append(r)}}
function drawChart(data){const c=$('#statsChart'),dpr=devicePixelRatio||1,w=c.clientWidth||600,h=230;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);if(!data.length)return;const max=Math.max(1,...data.map(v=>number(v.count))),left=Math.min(150,w*.38),row=(h-18)/data.length;x.font='12px system-ui';data.forEach((v,i)=>{const y=i*row+3,bw=(w-left-18)*number(v.count)/max;x.fillStyle='#e9e7ff';x.fillRect(left,y,bw,Math.max(8,row-5));x.fillStyle='#303247';x.textBaseline='middle';const label=String(v.text).length>18?String(v.text).slice(0,17)+'…':v.text;x.fillText(label,2,y+(row-5)/2);x.fillText(String(number(v.count)),left+bw+4,y+(row-5)/2)})}
async function adjust(w,delta){const wr=doc(db,'rooms',room,'words',w.id),mwr=doc(db,'rooms',room,'memberWords',`${user.uid}_${w.id}`),er=doc(collection(db,'rooms',room,'events'));try{await runTransaction(db,async tx=>{const [ws,ms]=await Promise.all([tx.get(wr),tx.get(mwr)]);if(!ws.exists())throw Error('項目がありません');const d=ws.data(),pc=ms.exists()?ms.data().count:0;if(delta<0&&pc<=0)throw Error('取り消せる記録がありません');tx.update(wr,{count:d.count+delta,totalScore:d.totalScore+d.points*delta,updatedAt:serverTimestamp()});const pd={uid:user.uid,wordId:w.id,count:pc+delta,updatedAt:serverTimestamp()};ms.exists()?tx.update(mwr,{count:pd.count,updatedAt:pd.updatedAt}):tx.set(mwr,pd);tx.set(er,{uid:user.uid,name:playerName(),wordId:w.id,wordText:d.text,delta,points:d.points,occurredAt:serverTimestamp()})})}catch(e){toast('変更できませんでした: '+e.message)}}
function openEditor(w){$('#editorTitle').textContent=w?'言葉を編集':'言葉を追加';$('#editId').value=w?.id||'';$('#wordText').value=w?.text||'';$('#wordPoints').value=w?.points??1;$('#editor').showModal()}
async function saveWord(e){e.preventDefault();const text=$('#wordText').value.trim(),points=Number($('#wordPoints').value),id=$('#editId').value;if(!text||!Number.isInteger(points))return;const ref=id?doc(db,'rooms',room,'words',id):doc(collection(db,'rooms',room,'words'));if(id)await runTransaction(db,async tx=>{const s=await tx.get(ref);tx.update(ref,{text,points,totalScore:s.data().count*points,updatedAt:serverTimestamp()})});else{const b=writeBatch(db);b.set(ref,{text,points,count:0,totalScore:0,order:Date.now(),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await b.commit()}$('#editor').close()}
async function removeWord(w){if(confirm(`「${w.text}」を削除しますか？`))await deleteDoc(doc(db,'rooms',room,'words',w.id))}
async function deleteMember(m){if(!isAdmin())return toast('管理者のみ削除できます');if(!confirm(`${m.name}さんと個人スコアを削除しますか？`))return;const q=await getDocs(query(collection(db,'rooms',room,'memberWords'),where('uid','==',m.uid))),b=writeBatch(db);q.forEach(d=>b.delete(d.ref));b.delete(doc(db,'rooms',room,'members',m.uid));await b.commit()}
function closeView(){unsubs.forEach(f=>f());unsubs=[];room='';$('#game').classList.add('hidden');$('#setup').classList.remove('hidden');toast('データを残して画面を閉じました')}
$('#joinBtn').onclick=()=>joinRoom(false).catch(e=>toast(e.message));$('#adminJoinBtn').onclick=()=>joinRoom(true).catch(e=>toast(e.message));$('#addBtn').onclick=()=>openEditor();$('#editorForm').onsubmit=e=>saveWord(e).catch(x=>toast(x.message));$('#cancelBtn').onclick=()=>$('#editor').close();$('#copyBtn').onclick=()=>navigator.clipboard.writeText(location.href).then(()=>toast('URLをコピーしました'));$('#leaveBtn').onclick=closeView;window.addEventListener('resize',()=>renderStats());init().catch(e=>{status('接続エラー','bad');toast(e.message)});
